-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 22:07:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cargas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cargas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cargas` DEFAULT CHARACTER SET utf8 ;
USE `cargas` ;

-- -----------------------------------------------------
-- Table `cargas`.`MarcasCamioes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`MarcasCamioes` (
  `idMarcasCamioes` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarcasCamioes`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Camioes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Camioes` (
  `idCamioes` INT NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  `Capacidade` INT NOT NULL,
  `MarcasCamioes_idMarcasCamioes` INT NOT NULL,
  PRIMARY KEY (`idCamioes`),
  UNIQUE INDEX `Placa_UNIQUE` (`Placa` ASC) VISIBLE,
  INDEX `fk_Camioes_MarcasCamioes_idx` (`MarcasCamioes_idMarcasCamioes` ASC) VISIBLE,
  CONSTRAINT `fk_Camioes_MarcasCamioes`
    FOREIGN KEY (`MarcasCamioes_idMarcasCamioes`)
    REFERENCES `cargas`.`MarcasCamioes` (`idMarcasCamioes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`StatusCargas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`StatusCargas` (
  `idStatusCargas` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStatusCargas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Paises` (
  `idPaises` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPaises`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Estados` (
  `idEstado` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Paises_idPaises` INT NOT NULL,
  PRIMARY KEY (`idEstado`),
  INDEX `fk_Estados_Paises1_idx` (`Paises_idPaises` ASC) VISIBLE,
  CONSTRAINT `fk_Estados_Paises1`
    FOREIGN KEY (`Paises_idPaises`)
    REFERENCES `cargas`.`Paises` (`idPaises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Cidades` (
  `idCidades` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidades`),
  INDEX `fk_Cidades_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Cidades_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `cargas`.`Estados` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Localizacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Localizacoes` (
  `idLocalizacoes` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Porto` TINYINT NOT NULL,
  `Cidades_idCidades` INT NOT NULL,
  PRIMARY KEY (`idLocalizacoes`),
  INDEX `fk_Localizacoes_Cidades1_idx` (`Cidades_idCidades` ASC) VISIBLE,
  CONSTRAINT `fk_Localizacoes_Cidades1`
    FOREIGN KEY (`Cidades_idCidades`)
    REFERENCES `cargas`.`Cidades` (`idCidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Funcionarios` (
  `idFuncionarios` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Identidade` INT NOT NULL,
  `Telefone` INT NOT NULL,
  PRIMARY KEY (`idFuncionarios`),
  UNIQUE INDEX `Identidade_UNIQUE` (`Identidade` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`MotoristasCat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`MotoristasCat` (
  `idMotoristasCat` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMotoristasCat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Motoristas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Motoristas` (
  `idMotoristas` INT NOT NULL,
  `NroCarteira` INT NOT NULL,
  `Funcionarios_idFuncionarios` INT NOT NULL,
  `MotoristasCat_idMotoristasCat` INT NOT NULL,
  PRIMARY KEY (`idMotoristas`),
  UNIQUE INDEX `NroCarteira_UNIQUE` (`NroCarteira` ASC) VISIBLE,
  INDEX `fk_Motoristas_Funcionarios1_idx` (`Funcionarios_idFuncionarios` ASC) VISIBLE,
  INDEX `fk_Motoristas_MotoristasCat1_idx` (`MotoristasCat_idMotoristasCat` ASC) VISIBLE,
  CONSTRAINT `fk_Motoristas_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `cargas`.`Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Motoristas_MotoristasCat1`
    FOREIGN KEY (`MotoristasCat_idMotoristasCat`)
    REFERENCES `cargas`.`MotoristasCat` (`idMotoristasCat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Controlador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Controlador` (
  `idControlador` INT NOT NULL,
  `Licenca` VARCHAR(45) NOT NULL,
  `Funcionarios_idFuncionarios` INT NOT NULL,
  PRIMARY KEY (`idControlador`),
  UNIQUE INDEX `Licenca_UNIQUE` (`Licenca` ASC) VISIBLE,
  INDEX `fk_Controlador_Funcionarios1_idx` (`Funcionarios_idFuncionarios` ASC) VISIBLE,
  CONSTRAINT `fk_Controlador_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `cargas`.`Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Cargas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Cargas` (
  `idCargas` INT NOT NULL,
  `DataSaida` DATE NOT NULL,
  `HoraSaida` DATETIME NOT NULL,
  `DataChegada` DATE NOT NULL,
  `HoraChegada` DATETIME NOT NULL,
  `Camioes_idCamioes` INT NOT NULL,
  `StatusCargas_idStatusCargas` INT NOT NULL,
  `Origem` INT NOT NULL,
  `Destino` INT NOT NULL,
  `Motoristas_idMotoristas` INT NOT NULL,
  `Controlador_idControlador` INT NOT NULL,
  PRIMARY KEY (`idCargas`),
  INDEX `fk_Cargas_Camioes1_idx` (`Camioes_idCamioes` ASC) VISIBLE,
  INDEX `fk_Cargas_StatusCargas1_idx` (`StatusCargas_idStatusCargas` ASC) VISIBLE,
  INDEX `fk_Cargas_Localizacoes1_idx` (`Origem` ASC) VISIBLE,
  INDEX `fk_Cargas_Localizacoes2_idx` (`Destino` ASC) VISIBLE,
  INDEX `fk_Cargas_Motoristas1_idx` (`Motoristas_idMotoristas` ASC) VISIBLE,
  INDEX `fk_Cargas_Controlador1_idx` (`Controlador_idControlador` ASC) VISIBLE,
  CONSTRAINT `fk_Cargas_Camioes1`
    FOREIGN KEY (`Camioes_idCamioes`)
    REFERENCES `cargas`.`Camioes` (`idCamioes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_StatusCargas1`
    FOREIGN KEY (`StatusCargas_idStatusCargas`)
    REFERENCES `cargas`.`StatusCargas` (`idStatusCargas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Localizacoes1`
    FOREIGN KEY (`Origem`)
    REFERENCES `cargas`.`Localizacoes` (`idLocalizacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Localizacoes2`
    FOREIGN KEY (`Destino`)
    REFERENCES `cargas`.`Localizacoes` (`idLocalizacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Motoristas1`
    FOREIGN KEY (`Motoristas_idMotoristas`)
    REFERENCES `cargas`.`Motoristas` (`idMotoristas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Controlador1`
    FOREIGN KEY (`Controlador_idControlador`)
    REFERENCES `cargas`.`Controlador` (`idControlador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`TiposMadeiras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`TiposMadeiras` (
  `idTiposMadeiras` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTiposMadeiras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`CargasMadeiras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`CargasMadeiras` (
  `TiposMadeiras_idTiposMadeiras` INT NOT NULL,
  `Cargas_idCargas` INT NOT NULL,
  INDEX `fk_CargasMadeiras_TiposMadeiras1_idx` (`TiposMadeiras_idTiposMadeiras` ASC) VISIBLE,
  INDEX `fk_CargasMadeiras_Cargas1_idx` (`Cargas_idCargas` ASC) VISIBLE,
  CONSTRAINT `fk_CargasMadeiras_TiposMadeiras1`
    FOREIGN KEY (`TiposMadeiras_idTiposMadeiras`)
    REFERENCES `cargas`.`TiposMadeiras` (`idTiposMadeiras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CargasMadeiras_Cargas1`
    FOREIGN KEY (`Cargas_idCargas`)
    REFERENCES `cargas`.`Cargas` (`idCargas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
