-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 20:42:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vendas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vendas` ;

-- -----------------------------------------------------
-- Schema vendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendas` DEFAULT CHARACTER SET utf8 ;
USE `vendas` ;

-- -----------------------------------------------------
-- Table `vendas`.`Fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendas`.`Fornecedores` ;

CREATE TABLE IF NOT EXISTS `vendas`.`Fornecedores` (
  `idFornecedores` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendas`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `vendas`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas`.`Compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendas`.`Compras` ;

CREATE TABLE IF NOT EXISTS `vendas`.`Compras` (
  `idCompras` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Data` DATE NOT NULL,
  `Valor_total` FLOAT NULL,
  `Fornecedores_idFornecedores` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idCompras`, `Fornecedores_idFornecedores`, `Usuarios_idUsuarios`),
  INDEX `fk_Compras_Fornecedores1_idx` (`Fornecedores_idFornecedores` ASC) VISIBLE,
  INDEX `fk_Compras_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Compras_Fornecedores1`
    FOREIGN KEY (`Fornecedores_idFornecedores`)
    REFERENCES `vendas`.`Fornecedores` (`idFornecedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compras_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `vendas`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendas`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `vendas`.`Produtos` (
  `idProdutos` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Qtd_stock` INT NOT NULL,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas`.`Compras_Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendas`.`Compras_Produtos` ;

CREATE TABLE IF NOT EXISTS `vendas`.`Compras_Produtos` (
  `Compras_idCompras` INT NOT NULL,
  `Produtos_idProdutos` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Valor_unitario` FLOAT NOT NULL,
  `Valor_total` FLOAT NOT NULL,
  `Desconto` FLOAT NULL,
  PRIMARY KEY (`Compras_idCompras`, `Produtos_idProdutos`),
  INDEX `fk_Compras_has_Produtos_Produtos1_idx` (`Produtos_idProdutos` ASC) VISIBLE,
  INDEX `fk_Compras_has_Produtos_Compras_idx` (`Compras_idCompras` ASC) VISIBLE,
  CONSTRAINT `fk_Compras_has_Produtos_Compras`
    FOREIGN KEY (`Compras_idCompras`)
    REFERENCES `vendas`.`Compras` (`idCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compras_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `vendas`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas`.`Historico_Precos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendas`.`Historico_Precos` ;

CREATE TABLE IF NOT EXISTS `vendas`.`Historico_Precos` (
  `idHistorico_Precos` INT NOT NULL,
  `Data_inicial` DATE NOT NULL,
  `Data_final` DATE NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Produtos_idProdutos` INT NOT NULL,
  PRIMARY KEY (`idHistorico_Precos`, `Produtos_idProdutos`),
  INDEX `fk_Historico_Precos_Produtos1_idx` (`Produtos_idProdutos` ASC) VISIBLE,
  CONSTRAINT `fk_Historico_Precos_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `vendas`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendas`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `vendas`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Identidade` INT NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas`.`Vendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendas`.`Vendas` ;

CREATE TABLE IF NOT EXISTS `vendas`.`Vendas` (
  `idVendas` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Valor_total` FLOAT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idVendas`, `Clientes_idClientes`, `Usuarios_idUsuarios`),
  INDEX `fk_Vendas_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_Vendas_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Vendas_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `vendas`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `vendas`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas`.`Vendas_Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendas`.`Vendas_Produtos` ;

CREATE TABLE IF NOT EXISTS `vendas`.`Vendas_Produtos` (
  `Vendas_idVendas` INT NOT NULL,
  `Produtos_idProdutos` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Valor_unitario` FLOAT NOT NULL,
  `Valor_total` FLOAT NOT NULL,
  `Desconto` FLOAT NULL,
  PRIMARY KEY (`Vendas_idVendas`, `Produtos_idProdutos`),
  INDEX `fk_Vendas_has_Produtos_Produtos1_idx` (`Produtos_idProdutos` ASC) VISIBLE,
  INDEX `fk_Vendas_has_Produtos_Vendas1_idx` (`Vendas_idVendas` ASC) VISIBLE,
  CONSTRAINT `fk_Vendas_has_Produtos_Vendas1`
    FOREIGN KEY (`Vendas_idVendas`)
    REFERENCES `vendas`.`Vendas` (`idVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `vendas`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendas`.`logs` ;

CREATE TABLE IF NOT EXISTS `vendas`.`logs` (
  `idlogs` INT NOT NULL,
  `Data_login` DATE NOT NULL,
  `Data_logout` DATE NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idlogs`, `Usuarios_idUsuarios`),
  INDEX `fk_logs_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_logs_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `vendas`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
